
modLoader = "javafml" #mandatory

loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "GNU"

[[mods]] #mandatory

modId = "rpg_exp_mg" #mandatory

version = "${file.jarVersion}" #mandatory

displayName = "RPG Expancion Magic Module" #mandatory

logoFile = "examplemod.png" #optional

credits = "Noir & Forge" #optional

authors = "Noir" #optional

description = '''
RPG Expancion Magic Module
Implement magic rpg like feature
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
# the modid of the dependency
modId = "forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[40,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
# Here's another dependency
[[dependencies.examplemod]]
mandatory = true
modId = "minecraft"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
ordering = "NONE"
side = "BOTH"
versionRange = "[1.18.2,1.19)"
